apiVersion: v2
name: rustdesk-stack
version: 0.3.0 # x-release-please-version
appVersion: "0.3.0" # x-release-please-version
description: Unofficial full-stack Helm chart for RustDesk Web Client, hbbs and hbbr
type: application
home: https://github.com/nomed/rustdesk-web-stack
sources:
  - https://github.com/nomed/rustdesk-web-stack
  - https://github.com/rustdesk/rustdesk
  - https://github.com/rustdesk/rustdesk-server
annotations:
  artifacthub.io/license: AGPL-3.0
