apiVersion: v2
name: rustdesk-web
version: 0.1.0
appVersion: "dev"
description: Unofficial Helm chart for the RustDesk Web Client deployment stack
type: application
home: https://github.com/nomed/rustdesk-web-stack
sources:
  - https://github.com/nomed/rustdesk-web-stack
  - https://github.com/rustdesk/rustdesk
